disabled_rules:
- trailing_whitespace
- line_length
- cyclomatic_complexity
- type_body_length
- file_length
force_try: error
function_parameter_count:
- 6 #warning
function_body_length:
- 70 #warning
